FROM alpine:latest

# Install deps
RUN apk update && apk upgrade
RUN apk add --no-cache git build-base cmake linux-headers
RUN git clone https://github.com/ruanformigoni/extfstools.git

WORKDIR extfstools

# Compile
RUN cmake -H. -Bbuild
RUN cmake --build build

# Copy static binary
RUN mkdir -p dist
RUN cp build/ext2rd dist/ext2rd
